version: "3.3"

services:
  portainer:
    image:  portainer/portainer:1.22.2
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:port.mathsgaze.com"
      placement:
        constraints: [node.role == manager]

  traefik:
    image: "traefik:v2.0.0"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8085:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      labels:
        - "traefik.frontend.rule=Host:traefik.mathsgaze.com"
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
      placement:
        constraints: [node.role == manager]
    networks:
      - traefik-net


networks:
  traefik-net:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
