#logLevel = "ERROR"
logLevel = "INFO"

defaultEntryPoints = ["https","http"]
endpoint = "tcp://127.0.0.1:2377"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "srv.mathsgaze.com"
watch = true
exposedByDefault = true

[acme]
email = "mavusogiftntokozo@gmail.com"
storage = "/acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
